# 파일 규격 버전 '3'만 적으면 3으로 시작하는 최신 버전을 사용
version: '3'

# services 밑으로 실행하려는 컨테이너 정의
services:
  postgresql1:
    container_name: main_db
    image: 'postgres:16.2-alpine'
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_MAIN_USER}
      - POSTGRES_PASSWORD=${POSTGRES_MAIN_PASSWORD}
      - POSTGRES_DB=${POSTGRES_MAIN_DB}
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    volumes:
      # pg의 환경 설정 파일
      - ${POSTGRES_MAIN_DATA_DIR}:/var/lib/postgresql/data
      # pg의 스키마
#      - ${POSTGRES_MAIN_INIT_DIR}:/docker-entrypoint-initdb.d
    ports:
      - '15432:5432'
    env_file:
      - .env
